# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a2bcbb46244989d432c8bc2e3c00964d1e5a4bd67d2be8ab268fb3b0be11ec9346ca4f068c9bd748081e5cac9787868e88e375e40b0c71a00a429c535b2f4d8

test:
  secret_key_base: 9c387849e9fdfe4ed99222749ad074ac95e46b7ed73472a199145bc6dc6f66fc260d16fe7f6812b49caaadd067f08d2bffe9611f1cf0ffaee2c3f8916c2bf4dc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
